[www]

; 1. UTILISATEUR SYSTEME
; Pour la securite, on ne fait jamais tourner PHP en tant que root.
; www-data est l'utilisateur Linux standard dedie aux serveurs web.
user = www-data
group = www-data

; 2. ECOUTE RESEAU (LE CHANGEMENT CLE POUR DOCKER)
; Par defaut, Debian ecoute sur un fichier local (.sock).
; On met 0.0.0.0:9000 pour ecouter sur le port TCP 9000 a travers le reseau Docker,
; afin que le conteneur NGINX puisse lui envoyer les fichiers PHP a executer.
listen = 0.0.0.0:9000
listen.owner = www-data
listen.group = www-data

; 3. GESTION DES OUVRIERS PHP (PROCESS MANAGER)
; dynamic signifie que PHP-FPM embauche ou libere des ouvriers selon l'affluence.
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; 4. VARIABLES D'ENVIRONNEMENT DOCKER
; Par defaut, PHP-FPM efface les variables d'environnement pour faire le menage.
; Avec clear_env = no, on lui interdit d'effacer nos variables (.env),
; car WordPress en a besoin pour connaitre le nom de la base de donnees !
clear_env = no

